repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
        exclude_types:
          - svg
          - pofile
        exclude: "(^LICENSE$)"
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: trailing-whitespace
        exclude_types:
          - svg
      - id: check-case-conflict
      - id: detect-private-key
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
        exclude: "(migrations)"
        args:
          - "--py38-plus"
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: "(migrations)"
